version: '2'
services:
    ucenter-app:
        image: ucenter
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://ucenter-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=ucenter-elasticsearch:9300
        ports:
            - 8078:8078
    ucenter-mssql:
        extends:
            file: mssql.yml
            service: ucenter-mssql
    ucenter-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ucenter-elasticsearch
